version: '3'
services:
  db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  crawl:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db